### ISSUE TITLE
Refactor config to be more generic

### ISSUE THREAD

**Issue by YashoSharma** [HackIllinois/api#101]
The current API configuration assumes that HackIllinois is the only organization that will use it, the configs should be made to be more abstract so other Hackathon's can use the API

**Comment by tommypacker** [comment]
I agree. The biggest thing is the attendee model which is super specific to what we have

**Comment by narendasan** [comment]
open-hackathon conversation would be super relevant here

**Comment by YashoSharma** [comment]
Correct me if I'm wrong @nmagerko but I think #140 addresses this issue to some degree?

**Comment by nmagerko** [comment]
@YashoSharma I believe it does. We shouldn't have any hackillinois-specific variables anywhere (besides on Travis but that's fine).
