### ISSUE TITLE
Support important time constants

### ISSUE THREAD

**Issue by redsn0w422** [HackIllinois/api#181]
Currently the iOS app has a handful of hardcoded constants used for important times and countdowns (https://github.com/HackIllinois/iOS/blob/dev/HackIllinois/Misc/Constants.swift), having these on the API and retrieved for the app would be a more flexible approach.

**Comment by ASankaran** [comment]
If we do this, the functionality should probably be included in the `upload` service under `/upload/datastore/` or `/upload/constants/`.
