### ISSUE TITLE
Add event filter endpoint

### ISSUE THREAD

**Issue by benpankow** [HackIllinois/api#231]
Currently, we have filtering endpoints for a few different services (`GET /user/filter`, for example). It would be nice to do something similar for events.

`GET /event/filter/?sponsor=Fulcrum`

In addition, searching within a particular time window would be helpful.

Something like:
`GET /event/filter/?minStartTime=1532202702&maxStartTime=1532212702`
 or
`GET /event/filter/?startTimeGt=1532202702`

- [x] Basic functionality
- [ ] Time range filtering

**Comment by benpankow** [comment]
@aryaman4

**Comment by aryaman4** [comment]
@benpankow I'm done with the code but testing on local is giving me a 403 forbidden. I'm guessing I'm supposed to add the admin token to the request but I'm not sure about the auth field which I'm supposed to use for postman.

**Comment by aryaman4** [comment]
I'm also not sure about how the mongo is set up structurally, so if there's any docs or if you could briefly explain, I'll set up a dummy on local for better testing.
