### ISSUE TITLE
Add blobstore delete endpoint

### ISSUE THREAD

**Issue by benpankow** [HackIllinois/api#242]
We currently have PUT, GET, and POST endpoints for the blobstore (https://docs.hackillinois.org/reference/services/Upload/). While our current use cases only include certain time constants, if we decide to use the blobstore for some sort of CRUD functionality, it would be good to be able to call `DELETE /upload/blobstore/exampleblob/` to remove the entry w/ id `exampleblob`.

Look to the event `DELETE` endpoint as reference.

**Comment by thomaslanghorst** [comment]
Is this issue still open for contribution? If so, I would like to help out.

**Comment by benpankow** [comment]
There's already a PR made for this issue (#254), but if you're interested in any of the other open issues, let me know!

**Comment by thomaslanghorst** [comment]
Oh, ok. I saw (#250) as closed but not merged. But I did not check the open PRs. I am new to open source. Thanks for helping me out. I will look for another open issue to contribute to.
