### ISSUE TITLE
Add registration filter endpoint

### ISSUE THREAD

**Issue by benpankow** [HackIllinois/api#244]
We currently have a `GET /user/filter/?key=value` endpoint [(see user docs)](https://docs.hackillinois.org/reference/services/User/) that lets us quickly query the list of users for specific criteria. It would be nice if we could do the same for registrations to quickly see a list of attendees from a certain school or of a certain year.

The endpoint should be something like `GET /registration/attendee/filter/?key=value`. The attendee endpoint is higher priority, but a mentor endpoint would also be good.

**Comment by ASankaran** [comment]
This kind of exists,  but it was implemented before we added mentor registration so it only filters through attendee registrations: 

https://github.com/HackIllinois/api/blob/2533c60c3cd0b0fe8653561c3da3cb7cad2c7175/services/registration/controller/controller.go#L23

Moving the endpoint to `GET /registration/attendee/filter/?key=value` and adding a mentor endpoint would definitely be good though.
