### ISSUE TITLE
Using a modern build system

### ISSUE THREAD

**Issue by narendasan** [HackIllinois/api#45]
Super cool this project has gotten to the point where a build system is required! You guys have put in a ton of work and the contributions to arbor are appreciated. I'd like to caution against using `make` just from an accessibility and maintainability perspective. Using something that is a bit easier to add and modify as the project changes will make it easier for others to contribute. 

A few recommendations:
Since the api is a monorepo a tool like `bazel` or `please` would make sense. Id probably recommend please (https://please.build/index.html) for this project since it doesnt add a jdk dependency and has the same nice monorepo behavior as `bazel` but if you are considering `bazel` take a look at `dazel` (https://github.com/nadirizr/dazel)

`Mage` is also nice if you want something closer to makefiles (https://github.com/magefile/mage)

**Comment by apache8080** [comment]
I think using please is probably the way to go because it handles go really well with both building binaries and tests. Also, please handles docker really well.

**Comment by ASankaran** [comment]
I'm a bit hesitant to switch to some of the newer build systems. `make` is the widely used standard so every developer has it installed and is familiar with it. 

Additionally the structure of the makefiles in this repo makes it very easy to add new services. Every service has a simple [makefile](https://github.com/HackIllinois/api/blob/documentation/services/event/Makefile), which passes off most of the work to a single common makefile. And adding a new service to deploy just requires adding the service to [this line](https://github.com/HackIllinois/api/blob/e50f4071fec352ab6c04c8d32d7f7823d417a800/Makefile#L8).

I do think that the build system should be documented better, but I'm not sure switching away from the standard is the right choice.

**Comment by narendasan** [comment]
> make is the widely used standard so every developer has it installed and **is familiar with it.**


Familiar enough to run `make -j12` perhaps, not familiar enough to modify and maintain a make based build system  

I think the main problem is make is very opaque as a system, make especially multi file make systems is very hard to track execution and build dependencies (not to mention the relative paths and the syntax don't help). I think the ease of expansion provided by systems like bazel or please are comparable if not better than make and the installation of these build systems is not more complicated than running a script (main drawback for bazel, which given your concerns is probably what fits best, is the jdk). I think on the multi year scale making this a stable and growing project is very dependent on using very clear and easy to understand tools so that transitions in developers are as simple as possible. 

For example:

```make 
export BASE_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

include ../../makefiles/common.mk
```
This is the standard service makefile.

```make
BASE_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
SUBDIRS := $(wildcard $(BASE_DIR)/*/.)
TARGETS := all test

SUBDIRS_TARGETS := $(foreach target,$(TARGETS),$(addsuffix $(target),$(SUBDIRS)))

.PHONY: $(TARGETS) $(SUBDIRS_TARGETS)

$(TARGETS): % : $(addsuffix %,$(SUBDIRS))
	@echo 'Finished running target "$*" on services'

$(SUBDIRS_TARGETS):
	$(MAKE) -C $(@D) $(@F:.%=%)
```
This is the service level makefile 

```make 
BASE_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
SUBDIRS := $(wildcard $(BASE_DIR)/*/.)
SUBDIRS := $(BASE_DIR)/services/. $(BASE_DIR)/gateway/. $(BASE_DIR)/common/.

TARGETS := all test
SUBDIRS_TARGETS := $(foreach target,$(TARGETS),$(addsuffix $(target),$(SUBDIRS)))
DEPLOY_GATEWAY_TARGETS := gateway
DEPLOY_SERVICE_TARGETS := auth user registration decision rsvp checkin upload mail event stat
DEPLOY_TARGETS := $(DEPLOY_GATEWAY_TARGETS) $(DEPLOY_SERVICE_TARGETS)

.PHONY: $(TARGETS) $(SUBDIRS_TARGETS)

$(TARGETS): % : $(addsuffix %,$(SUBDIRS))
	@echo 'Finished running target "$*"'

$(SUBDIRS_TARGETS):
	$(MAKE) -C $(@D) $(@F:.%=%)

.PHONY: run
run:
	@$(BASE_DIR)/scripts/run.sh

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: deploy
deploy:
	mkdir -p $(BASE_DIR)/build/
	$(foreach target,$(DEPLOY_TARGETS),mkdir -p $(BASE_DIR)/build/$(target)/;cp $(GOPATH)/bin/hackillinois-api-$(target) $(BASE_DIR)/build/$(target)/hackillinois-api-$(target);)
	$(foreach target,$(DEPLOY_GATEWAY_TARGETS),cp $(BASE_DIR)/$(target)/Dockerfile $(BASE_DIR)/build/$(target)/Dockerfile;)
	$(foreach target,$(DEPLOY_SERVICE_TARGETS),cp $(BASE_DIR)/services/$(target)/Dockerfile $(BASE_DIR)/build/$(target)/Dockerfile;)
	$(foreach target,$(DEPLOY_GATEWAY_TARGETS),cp $(BASE_DIR)/$(target)/buildspec.yml $(BASE_DIR)/build/$(target)/buildspec.yml;)
	$(foreach target,$(DEPLOY_SERVICE_TARGETS),cp $(BASE_DIR)/services/$(target)/buildspec.yml $(BASE_DIR)/build/$(target)/buildspec.yml;)
	mkdir -p $(BASE_DIR)/deploy/
	$(foreach target,$(DEPLOY_TARGETS),mkdir -p $(BASE_DIR)/deploy/api-$(target)/;cd $(BASE_DIR)/build/$(target);zip -r $(BASE_DIR)/deploy/api-$(target)/api-$(target).zip *; cd $(CURDIR);)
	rm -rf build/

.PHONY: release
release: all
	$(foreach target,$(DEPLOY_TARGETS),cp $(GOPATH)/bin/hackillinois-api-$(target) $(BASE_DIR)/release/hackillinois-api-$(target);)
	cd $(BASE_DIR)/release/ && docker build -t hackillinois-api:release . && cd $(CURDIR)
	docker save -o $(BASE_DIR)/release/hackillinois-api-image.tar hackillinois-api:release
	docker image rm -f hackillinois-api:release
	$(foreach target,$(DEPLOY_TARGETS),rm $(BASE_DIR)/release/hackillinois-api-$(target);)
```
and then this is the top level. Someone eventually is going to have to read all of this and figure it out and because its so templatized its going to be be hard and unfortunately people hit google before they hit the docs. That is only from the less experience case. Perhaps you bring someone on who is a make god, the complexity of the system will only go up as more an more build system features are added. 

Something like bazel or please would solely consist of some repo level configurations, entailing third party libraries and then a BUILD file like so per package:
```BUILD
go_library(
    name = "go_default_library",
    srcs = ["server.go"],
    importpath = "github.com/hackillinois/api/gateway",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_arbor_dev_arbor//:go_default_library",
        "@com_github_hackillinois_api//gateway/config:go_default_library",
        "@com_github_hackillinois_api//gateway/services:go_default_library",
    ],
)

go_binary(
    name = "gateway",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

```
Bazel actually has a tool to scaffold the build system for you (one of the old ACM top4 members wrote a great blog post on setting up bazel for go - http://brendanjryan.com/golang/bazel/2018/05/12/building-go-applications-with-bazel.html)  so most of the work can be autogenerated then customized later as needed.

The advantages here are that's its clear what is going on, what the targets are, and also what the dependencies of the targets are, you can also vendor and reproduce third party dependencies, the language is pythonic so its easy to extend as you need more complex functionality and there are also rules to do things like building and deploying dockerfiles. I also think there is enough success stories with something like bazel especially in a monorepo style project that while it might not be "standard" it is common enough to find help. 

Imo the main issue isn't that its hard right now. Its that this is an API who's dev team by definition has like a 1-2 year turn over. The design challenges for projects of this type are very different from normal projects. Accessibility is a top level priority and so imo guard rails matter. This is the 5th api I've seen in 5 years (we dumped one halfway through the year in 2016) and while you are able to configure this system and also are disciplined enough to not dump everything into it, I have seen enough make build systems to know this sort of stuff gets nasty really fast. 

I think in general a design goal worth perusing is that this should be sustainable as a project with you having only to clarify architecture level for developers as time goes on instead of having the core maintainers doing the majority of the work. Avoid templating where you can, minimized dependencies, make things human readable and make onboarding simple

**Comment by ASankaran** [comment]
Going to close this for now since the make based system has been simplified. Next year's systems director can reopen if there is a need to migrate away from make.
