### ISSUE TITLE
Migrate QR Codes to User Service

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api#46]
Currently we have QR Code generation in the checkin service, but it makes more sense for it to be in the user service since it is used in many places and it is a way to identify a user.

- [x] Move QR Code generation to the user service
- [x] Change QR Code fields to only contain user information, ie. `userid`, `email`, etc.

**Comment by PradyumnaShome** [comment]
What fields do we want on the QR code? Right now, the only user-service related field is `userId`.

**Comment by ASankaran** [comment]
We probably only need `userId` embedded within the QR code since everything else can be retrieved based on that piece of information.
