### ISSUE TITLE
User service: Add Route for GetFilteredUserInfo

### ISSUE THREAD

**Issue by PradyumnaShome** [HackIllinois/api#48]
Controller function at: https://github.com/HackIllinois/api/blob/5ef2301fc16447a435c84176a6105e4acd532aae/services/user/controller/controller.go#L67

Location of proposed Route: https://github.com/HackIllinois/api/blob/5ef2301fc16447a435c84176a6105e4acd532aae/gateway/services/user.go#L34

This should be restricted to `Admin`s.

**Comment by ASankaran** [comment]
Duplicate of #24
