### ISSUE TITLE
Admin Utililties

### ISSUE THREAD

**Issue by YashoSharma** [HackIllinois/api#55]
We lack utilities for managing the user base of the api, things such as role assignment. Basic querying of statistics and event management shouldn't need to be done at the bare bones level.

**Comment by ASankaran** [comment]
These are sufficiently small utilities which it's probably simplest to implement using python scripts.

- [ ] Registration dump to CSV
- [ ] Event upload to API
- [ ] Role modification
- [ ] Stats query
