### ISSUE TITLE
Add event favorites

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api#9]
We want to allow users to mark events are "favorite" so that mobile apps can display these events at the top of the event list for users.

- [x] Allow users to favorite events
- [x] Allow users to retrieve a list of their favorite events

**Comment by itsmesatwik** [comment]
I was thinking adding `favourites` key to the user_info.go which has a list of the event names starred by the user. Additionally would need to have a `MarkAsFavourite()` and `GetFavourites()`. What do you think about this route? @ASankaran @PradyumnaShome

**Comment by itsmesatwik** [comment]
Working on it
